### ISSUE TITLE
Add factory method to instantiate an Adapter subclass for the specified cluster

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#6]
Usage:

```ruby
@torque_adapter = OodJob::Adapter.create(mycluster)
```

How?

The resource mgr's (`mycluster.resource_mgr`) class name is `Torque`, so by convention we instantiate a new `Torque`. If we add optional "type" attribute to resource_mgr or server, this could be used as well to determine the adapter subclass to instantiate by convention. So a `mycluster.resource_mgr` of class OSCCustomTorque would have the type be `Torque`.

**Comment by nickjer** [comment]
I have also been thinking about this possibility. The basic concept is that the `OodCluster::Server` object (in particular the ones intending to be resource managers) specifies its adapter whether implicitly or explicitly. Only reason I am hesitant against this, is because although we don't specify `OodJob` anywhere in the code, it still feels like it knows about `OodJob` and vice-versa. Also specifying external custom adapters is difficult (e.g. `MyCenter::Adapters::Torque`).

Note: What you suggest is kind-of what I already do in [ood_reservations](https://github.com/OSC/ood_reservations) (aside from specifying the type, since it can use both resource_mgr and scheduler). So maybe it is fine for now.

Another option is that the adapter is explicitly specified in `OodAppkit::ClusterDecorator` through the global cluster config.

```yaml
#/etc/ood/config/clusters.d/ruby.yml
v1:
  title: "Ruby"
  adapter: "OodJob::Adapters::Torque"
  cluster:
    ...
```

where now we push the knowledge of `OodJob` to `OodAppkit` and take it out of `OodCluster` (although you can argue it was never in there). This unfortunately makes `ood_job` a dependency in `ood_appkit`, which may or may not be a bad thing.

I guess you could also make the same argument for `ood_reservations` being a requirement of `ood_appkit` as well. In the end it seems like a tough call.

**Comment by ericfranz** [comment]
Up to this point, we have had no cluster config, and the only way to use a custom job adapter in osc-machete was to instantiate it in the code of your app and inject it into Job to use it. Most of our apps could get by without a custom torque adapter, and the few that needed custom ones were OSC specific apps.

With the new ood_job gem, the problems that required us to add a custom job adapter have been addressed. All of our apps will be able to use ood_job without creating a custom job adapter.

A cluster resource manager class is an object whose only purpose right now is to store information that is useful by apps and job adapters. The only use case I can imagine needing a custom cluster resource manager class is if you need extra information that a custom job adapter class would make use of, since currently resource manager information from ood_clusters is not used outside of ood_job.

But if you are providing a custom cluster resource manager class for a custom job adapter class, you could ensure that both follow the appropriate naming convention. MyCustomTorque resource manager would work with MyCustomTorque adapter.

Thus, we can probably get by for now by following the convention:

> The resource mgr's (mycluster.resource_mgr) class name is Torque, so by convention we instantiate a corresponding Torque job adapter class

And postpone adding any cleverness like explicitly specifying an adapter class to load.

For now, if I want to test a custom Torque adapter, I can just use that adapter explicitly in code instead of relying on a `OodJob::Adapter.create` factory method.

In the future, when we want to add the ability to add a custom job adapter and custom resource manager, this is actually a 2 step problem:

1. how to make these custom classes available in the LOAD_PATH to all of the apps (and gems)
2. how to properly alter the cluster config so these classes are used in the appropriate cases

We have only talked about step 2 in this.

Though, after thinking about it, I guess one instance where a site specific resource_mgr class would be useful would be if we wanted to provided "default_script" options there; for example, setting the account string. This is easy to do via ruby code.

**Comment by ericfranz** [comment]
Other attributes that would be nice to set defaults for: number of nodes and ppn

**Comment by nickjer** [comment]
> since currently resource manager information from ood_clusters is not used outside of ood_job.

It is used in the `ood_reservations` library

> The resource mgr's (mycluster.resource_mgr) class name is Torque, so by convention we instantiate a corresponding Torque job adapter class

This is similarly to how `ood_reservations` does this through the `OodReservations::Query.build` method:

  - https://github.com/OSC/ood_reservations/blob/210d8e7c14a14ad1df11dd7911c80389ada06981/lib/ood_reservations/query.rb#L10-L20
  - https://github.com/OSC/ood_reservations/blob/210d8e7c14a14ad1df11dd7911c80389ada06981/lib/ood_reservations/queries/torque_moab.rb#L13-L21

It goes through a list of registered adapters selecting the first adapter whose cluster requirements match the passed in cluster object. Only difference with your suggestion is that it checks the full class name, so that there is a guarantee of compatibility.

Although I am not completely satisfied with this approach, but I have no alternatives right now as I haven't given this too much thought recently.

**Comment by nickjer** [comment]
Another benefit of:

```yaml
# /etc/ood/config/clusters.d/ruby.yml
--
v1:
  title: "Ruby"
  adapter: "OodJob::Adapters::Torque"
  cluster:
    ...
```

is that we can store the adapter from the config as a string. So that the necessary gem to use that class is not required.

We would design a getter as such:

```ruby
class ClusterDecorator ...
  ...

  # Exception raised if adapter is not specified or is missing
  class MissingAdapter < StandardError; end

  # OodJob::Adapter class used by this cluster
  # @raise [MissingAdapter] if unable to find adapter class
  # @return [Class] the adapter class
  def adapter
    @adapter.constantize
  rescue NameError => e
    raise MissingAdapter, e.message
  end
end
```

The idea is that we don't need the `ood_job` gem in our apps unless the developer makes an explicit call to `OodAppkit::ClusterDecorator#adapter`.

A developer can use it in their code as such:

```ruby
begin
  oakley = OodAppkit.clusters["oakley"]
  oakley.adapter.new(cluster: oakley).submit( ... )
rescue OodAppkit::ClusterDecorator::MissingAdapter => e
  # handle error here
end
```

It can probably be shortened up a bit by redefining `OodAppkit::ClusterDecorator#adapter` to be:

```ruby
  def adapter
    @adapter.constantize.new(cluster: self)
  rescue NameError => e
    raise MissingAdapter, e.message
  end
```

But then `OodAppkit::ClusterDecorator#adapter` knows about `OodJob::Adapter.new`'s initialization arguments. That is something that should probably be handled in `OodJobRails::Adapter`.

Note: The solution here can also be extended to the similar `ood_reservations` gem adapter issue.

**Comment by nickjer** [comment]
To tack on to my previous response further, we could also include to `ClusterDecorator#valid?`:

```
    def valid?(method = :cluster)
      Object.const_defined?(@adapter) && @validators.fetch(method.to_sym, []).all? { |v| v.success? }
    end
```

That way if the proper gem libraries aren't loaded, the apps won't crash. They will just hide that corresponding cluster, assuming the apps take advantage of `ClusterDecorator#valid?`.

**Comment by ericfranz** [comment]
So a short term solution is:

1. add `OodCluster::Servers::Lsf` and `OodCluster::Servers::Slurm`
2. add `OodJob::Adapters::Lsf` and `OodJob::Adapters::Slurm`
3. add `ClusterDecorator#adapter` that given a `OodCluster::Servers::Lsf` will instantiate a `OodJob::Adapters::Lsf` instance
4. update MyJobs to use `ClusterDecorator#adapter` (how do we filter out clusters with missing adapters?)

Or we implement our ood_core gem solution now and couple that with the release of Slurm and LSF support.

**Comment by ericfranz** [comment]
Actually the short term solution is this:

1. add `OodCluster::Servers::ResourceMgr` with the attribute `type` set to `torque`, `slurm` or `lsf`
2. add `OodJob::Adapters::Lsf` and `OodJob::Adapters::Slurm`
3. add `ClusterDecorator#adapter` that
   1. given an `OodCluster::Servers::Torque` for resource_mgr instantiates `OodJob::Adapters::Torque`
   2. given an `OodCluster::Servers::ResourceMgr` for resource_mgr with attribute `type` set to a string instantiates `OodJob::Adapters::#{type.camelize}`
4. update MyJobs to use `ClusterDecorator#adapter` (how do we filter out clusters with missing adapters?)

**Comment by ericfranz** [comment]
Example yaml config for v1 yaml:

```yaml
resource_mgr:
  type: "OodCluster:Servers::ResourceMgr"
  data:
    host: "owens-batch.ten.osc.edu"
    type: torque
    lib: "/opt/torque/lib64"
    bin: "/opt/torque/bin"
    version: "6.0.1"
```

**Comment by nickjer** [comment]
This is currently implemented in [ood_core](https://github.com/OSC/ood_core) as:

```ruby
OodCore::Job::Adapter.build job_config
```

where `job_config` looks like:

```ruby
job_config = {
    adapter: "torque",
    host: "oak-batch.osc.edu",
    lib: "/opt/torque/lib64",
    bin: "/opt/torque/bin"
  }
```
